# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/maxime/Project/Pick_Crater/pick_app/main_window_pickapp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 1081)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(41, 11, 964, 1018))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.SAR_change = QtWidgets.QSlider(self.widget)
        self.SAR_change.setOrientation(QtCore.Qt.Horizontal)
        self.SAR_change.setObjectName("SAR_change")
        self.verticalLayout.addWidget(self.SAR_change)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.SARImage = QtWidgets.QWidget(self.widget)
        self.SARImage.setMinimumSize(QtCore.QSize(800, 800))
        self.SARImage.setObjectName("SARImage")
        self.SARLayout = QtWidgets.QVBoxLayout(self.SARImage)
        self.SARLayout.setObjectName("SARLayout")
        self.horizontalLayout.addWidget(self.SARImage)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.SAR_greyscale = QtWidgets.QSlider(self.widget)
        self.SAR_greyscale.setOrientation(QtCore.Qt.Vertical)
        self.SAR_greyscale.setObjectName("SAR_greyscale")
        self.horizontalLayout.addWidget(self.SAR_greyscale)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1025, 21))
        self.menuBar.setMinimumSize(QtCore.QSize(0, 10))
        self.menuBar.setDefaultUp(True)
        self.menuBar.setNativeMenuBar(False)
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtWidgets.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menuBar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Close = QtWidgets.QAction(MainWindow)
        self.action_Close.setObjectName("action_Close")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_Close_2 = QtWidgets.QAction(MainWindow)
        self.action_Close_2.setObjectName("action_Close_2")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.action_Open_2 = QtWidgets.QAction(MainWindow)
        self.action_Open_2.setObjectName("action_Open_2")
        self.action_Save_csv = QtWidgets.QAction(MainWindow)
        self.action_Save_csv.setObjectName("action_Save_csv")
        self.action_Open_3 = QtWidgets.QAction(MainWindow)
        self.action_Open_3.setObjectName("action_Open_3")
        self.action_Open_csv = QtWidgets.QAction(MainWindow)
        self.action_Open_csv.setObjectName("action_Open_csv")
        self.menu_File.addAction(self.action_Save_csv)
        self.menu_File.addAction(self.action_Open_csv)
        self.menuBar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MainWindow)
        self.SAR_greyscale.valueChanged['int'].connect(MainWindow.update) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.action_Close.setText(_translate("MainWindow", "&Close"))
        self.action_2.setText(_translate("MainWindow", "&Open"))
        self.action_2.setShortcut(_translate("MainWindow", "Meta+O"))
        self.action_Close_2.setText(_translate("MainWindow", "&Save"))
        self.action_Close_2.setShortcut(_translate("MainWindow", "Meta+S"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.action_Open_2.setText(_translate("MainWindow", "&Open"))
        self.action_Save_csv.setText(_translate("MainWindow", "&Save"))
        self.action_Open_3.setText(_translate("MainWindow", "&Open"))
        self.action_Open_csv.setText(_translate("MainWindow", "&Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
